<?php

/**
 * Legacy URL 301 redirects (old site → new permalinks).
 *
 * Map: inc/data/legacy-redirects.json (generated by
 * .vscode/parsing/scripts/generate-redirects.mjs).
 *
 * @package ksenonspb
 */

if (! defined('ABSPATH')) {
	exit;
}

if (! function_exists('ksenon_get_legacy_redirects_map')) {
	/**
	 * @return array<string, string> Normalized old path => new path.
	 */
	function ksenon_get_legacy_redirects_map()
	{
		static $map = null;

		if (null !== $map) {
			return $map;
		}

		$map      = array();
		$file_path = KSENON_DIR . '/inc/data/legacy-redirects.json';

		if (! is_readable($file_path)) {
			return $map;
		}

		$raw  = file_get_contents($file_path);
		$data = is_string($raw) ? json_decode($raw, true) : null;

		if (! is_array($data) || empty($data['map']) || ! is_array($data['map'])) {
			return $map;
		}

		foreach ($data['map'] as $old_path => $new_path) {
			if (! is_string($old_path) || ! is_string($new_path)) {
				continue;
			}
			$old = ksenon_normalize_redirect_path($old_path);
			$new = ksenon_normalize_redirect_path($new_path);
			if ('' === $old || $old === $new) {
				continue;
			}
			$map[ $old ] = $new;
		}

		return $map;
	}
}

if (! function_exists('ksenon_normalize_redirect_path')) {
	/**
	 * Decode, lowercase, ensure leading/trailing slash.
	 *
	 * @param string $path Request path or mapped path.
	 * @return string
	 */
	function ksenon_normalize_redirect_path($path)
	{
		$path = (string) $path;
		$path = strtok($path, '?') ?: $path;
		$path = strtok($path, '#') ?: $path;

		$decoded = rawurldecode($path);
		if (function_exists('mb_strtolower')) {
			$decoded = mb_strtolower($decoded, 'UTF-8');
		} else {
			$decoded = strtolower($decoded);
		}

		if ('' === $decoded || '/' !== $decoded[0]) {
			$decoded = '/' . ltrim($decoded, '/');
		}

		if ('/' !== substr($decoded, -1)) {
			$decoded .= '/';
		}

		return $decoded;
	}
}

if (! function_exists('ksenon_get_request_path_for_redirect')) {
	/**
	 * @return string Normalized path for the current request.
	 */
	function ksenon_get_request_path_for_redirect()
	{
		$uri = isset($_SERVER['REQUEST_URI']) ? wp_unslash((string) $_SERVER['REQUEST_URI']) : '/';
		$path = (string) wp_parse_url($uri, PHP_URL_PATH);
		if ('' === $path) {
			$path = '/';
		}

		return ksenon_normalize_redirect_path($path);
	}
}

if (! function_exists('ksenon_should_skip_legacy_redirect')) {
	/**
	 * @return bool
	 */
	function ksenon_should_skip_legacy_redirect()
	{
		if (is_admin()) {
			return true;
		}

		if (wp_doing_ajax() || wp_doing_cron()) {
			return true;
		}

		if (defined('REST_REQUEST') && REST_REQUEST) {
			return true;
		}

		if (defined('WP_CLI') && WP_CLI) {
			return true;
		}

		return false;
	}
}

add_action(
	'template_redirect',
	static function () {
		if (ksenon_should_skip_legacy_redirect()) {
			return;
		}

		$map = ksenon_get_legacy_redirects_map();
		if (! $map) {
			return;
		}

		$path = ksenon_get_request_path_for_redirect();
		if (! isset($map[ $path ])) {
			return;
		}

		$target = $map[ $path ];
		if ($target === $path) {
			return;
		}

		$location = home_url($target);
		wp_safe_redirect($location, 301);
		exit;
	},
	1
);
